### ISSUE TITLE
Icon size

### ISSUE THREAD

**Issue by seb-vial** [Birssan/grav-plugin-about-me#20]
As @gbschenkel pointed out, it might be useful to be able to pick a size for FontAwesome icons. According to the doc there is a way to change the icon size by using a class. https://fontawesome.com/how-to-use/on-the-web/styling/sizing-icons
The way I see this, there should be a select box with all the available classes from FontAwesome (with corresponding size in **em**). I'm just wondering if this select box should be available for every social media icon in the settings, or should it just be set for all the icons at once (meaning all the icons would have the same size, always) ?

**Comment by gbschenkel** [comment]
I think we could have a 'size' inside social_pages to set the default size for all them, and other inside the specific page, for overwrite the default icon size, like to inform that one is your main social network/page:

Example:
```
social_pages:
  enabled: true
  use_font_awesome: true
  size: 10 (pixels?)
  pages:
    facebook:
      icon_type: b
      icon: facebook
      title: Facebook
      position: 1
    twitter:
      icon_type: b
      icon: twitter
      title: Twitter
      position: 2
      size: 15 (overwrite the default size)
      url: 
```
