### ISSUE TITLE
Problem with avatars in Grav 1.1 RC3

### ISSUE THREAD

**Issue by paulcmal** [Birssan/grav-plugin-about-me#3]
After modifying settings in the plugin admin interface, the aboutme page cannot be rendered anymore :

> "An exception has been thrown during the rendering of a template ("Array to string conversion") in "partials/aboutme.html.twig" at line 4."

Digging around, I found that picture_src is not storing just the filename with Grav 1.1 but saving a full array of info about the file, hence the error.

Sample data from aboutme.yaml after uploading :

```
picture_src:
  user/plugins/aboutme/assets/avatars/100px-PlaceHolder.png:
    name: 100px-PlaceHolder.png
    path: user/plugins/aboutme/assets/avatars/100px-PlaceHolder.png
    type: image/png
    size: 30971
    file: user/plugins/aboutme/assets/avatars/100px-PlaceHolder.png
    route: null
```
